/**
 * World to screen the way $6000 does it, end to end and entirely in fixed point.
 *
 * `diskProjection.ts` is generated by a fit: it rotates with floats, uses focal lengths of
 * 230.90 and 212.80 solved for from captures, and rotates by two angles. The machine does
 * none of that. It builds a three-angle Q15 matrix with its own broken trig (`diskRotation.ts`),
 * scales the three camera axes by a per-object triple, multiplies through a 16-bit routine that
 * is not `a * b / 32768`, and divides with a non-restoring divide (`diskProjectionFixed.ts`).
 *
 *   $62CB  nine bytes of display list -> $90-$98   camera position, then pitch, bank, heading
 *   $62D5  JSR $654E                               build the matrix
 *   $6631  scale row 0/1/2 by $600E/$6010/$6012    the camera-axis scale
 *   $672B  the model point minus $90-$95           -> $AB/$AD/$AF
 *   $675B  M . that, through $633D and $67D4       -> $60-$65
 *   $6274  LDY #$60 / LDX #$9F / JSR $68A1         -> two screen bytes
 *   $6DD5  x + 70, doubled; 95 - y                 -> the hi-res page
 *
 * The fitted focal lengths turn out to be the scale: `2 * 69 * factor0 / factor2` is 231.42
 * and `62 * factor1 / factor2` is 212.93, against 230.90 and 212.80. So the fit was measuring
 * this, one step removed.
 *
 * Checked against 60 world points trapped from a live render by `oracle/probe_pipeline.mjs`,
 * at every stage: the translated vector, camera space, the two screen bytes, and the final
 * pixel. See `oracle/pipeline_parity.mjs`.
 */

import {
  buildMatrix654E, applyObjectScale, toCameraSpace6730, mul635C,
  SNAPSHOT_SCALE, type RotationMatrix,
} from './diskRotation';
import {
  project68A1, project68A1ToScreen, SNAPSHOT_OPERANDS, type ProjectionOperands,
} from './diskProjectionFixed';
import { NEAR_Z, type Vec3 } from './diskProjection';

export { NEAR_Z };

/** Everything $6000 needs about one object, as the display list hands it over. */
export interface ObjectView {
  /** $90-$95 - the camera, in model units. */
  camera: Vec3;
  /** $96, $97, $98 - byte angles, 256 to the turn. */
  pitch: number;
  bank: number;
  heading: number;
  /** $600E-$6013 - the camera-axis scale. */
  scale: readonly [number, number, number];
  /** $68BA/$68C0/$68DD/$68E3 - the clamp limits and offsets. */
  ops: ProjectionOperands;
}

/** The flight snapshot's own view, as `oracle/probe_pipeline.mjs` read it at $6631. */
export const SNAPSHOT_VIEW: Omit<ObjectView, 'camera'> = {
  pitch: 0, bank: 0, heading: 0,
  scale: SNAPSHOT_SCALE,
  ops: SNAPSHOT_OPERANDS,
};

/**
 * $654E then $6631 - the matrix an object is actually transformed by.
 *
 * Worth hoisting out of any per-vertex loop: the machine builds it once per object, which is
 * what `$62D5` and the fall-through at `$6631` amount to.
 */
export function viewMatrix(view: ObjectView): RotationMatrix {
  return applyObjectScale(buildMatrix654E(view.pitch, view.bank, view.heading), view.scale);
}

const clamp16 = (v: number): number => (v > 32767 ? 32767 : v < -32768 ? -32768 : Math.round(v));

/**
 * $672B and $675B - a world point into camera space, with the matrix already built.
 *
 * The machine works in whole model units throughout, so the coordinates are rounded and held
 * to sixteen bits on the way in. A clipped endpoint is the only thing that arrives fractional,
 * and rounding it is the one place this departs from the disk - the disk never has one,
 * because it clips on the screen rather than at a near plane.
 */
export function toCameraSpaceFixed(p: Vec3, camera: Vec3, m: RotationMatrix): Vec3 {
  const d = toCameraSpace6730(
    [clamp16(p.x), clamp16(p.y), clamp16(p.z)],
    [clamp16(camera.x), clamp16(camera.y), clamp16(camera.z)],
    m,
  );
  return { x: d[0], y: d[1], z: d[2] };
}

/**
 * $68A1 and $6DD5 - camera space to a pixel, or null behind the near plane.
 *
 * The machine has no near plane: `$6468` divides by a negative z quite happily and `$68A1`
 * returns a point that is mirrored through the origin, which the screen clipping at `$61A9`
 * then usually throws away. The port cannot rely on that, because `insideClip()` would let a
 * mirrored point through whenever it happened to land on the panel - so the same `z < NEAR_Z`
 * test `projectCameraSpace()` uses is kept.
 */
export function projectCameraSpaceFixed(
  d: Vec3,
  ops: ProjectionOperands = SNAPSHOT_OPERANDS,
): { x: number; y: number } | null {
  if (d.z < NEAR_Z) return null;
  return project68A1ToScreen(clamp16(d.x), clamp16(d.y), clamp16(d.z), ops);
}

/** The two screen bytes as $68A1 writes them, before $6DD5 maps them. */
export function projectCameraSpaceBytes(
  d: Vec3,
  ops: ProjectionOperands = SNAPSHOT_OPERANDS,
): { sx: number; sy: number } {
  return project68A1(clamp16(d.x), clamp16(d.y), clamp16(d.z), ops);
}

/** The whole chain for a single point, when there is no loop to hoist the matrix out of. */
export function projectWorldPointFixed(
  p: Vec3,
  view: ObjectView,
): { x: number; y: number } | null {
  return projectCameraSpaceFixed(toCameraSpaceFixed(p, view.camera, viewMatrix(view)), view.ops);
}

/** Re-exported so callers do not have to reach past this module for the primitive. */
export { mul635C };

/**
 * $67EF - the camera-space outcode, four bits.
 *
 * Each plane is tested by a 16-bit add or subtract followed by the `BMI/BVC/BVS` dance that
 * asks whether N and V disagree, which is the signed "is this negative" test:
 *
 *     $67F1  x + z < 0   ->  $40      the left plane,   x = -z
 *     $6804  z - x < 0   ->  $20      the right plane,  x = z
 *     $6819  y + z < 0   ->  $10      the bottom plane, y = -z
 *     $682E  z - y < 0   ->  $08      the top plane,    y = z
 *
 * So the frustum is |x| <= z and |y| <= z: ninety degrees each way, in camera space and after
 * the object scale. That is exactly the region where `$68A1` does not wrap - x/z of 1 is the
 * clamp limit - which is why the disk never draws the folded-over points a naive port does.
 * A point behind the camera always has a bit set, since |x| <= z is impossible for z < 0, so
 * there is no separate near-plane test.
 *
 * `$6848` is the same routine for the second slot at $68, writing $6E instead of $66.
 */
export const OUT_LEFT = 0x40;
export const OUT_RIGHT = 0x20;
export const OUT_BOTTOM = 0x10;
export const OUT_TOP = 0x08;

export function outcode67EF(d: Vec3): number {
  let o = 0;
  if (d.x + d.z < 0) o |= OUT_LEFT;
  if (d.z - d.x < 0) o |= OUT_RIGHT;
  if (d.y + d.z < 0) o |= OUT_BOTTOM;
  if (d.z - d.y < 0) o |= OUT_TOP;
  return o;
}

/** $615E - `LDA #$0A / STA $B1`, the clipper's iteration budget. */
export const CLIP_ROUNDS = 10;

/**
 * $61B7 - clip a camera-space segment to the frustum, or drop it.
 *
 * `JSR $61A9 / JSR $618E / BNE $620F` transforms both ends, takes both outcodes and rejects
 * the segment outright when `$66 AND $6E` is nonzero - both ends outside the same plane. Then
 * it alternates: while an end is outside, pull it onto the plane that is failing ($6979 for
 * the far end, $695F for the near one, which is $6979 between two swaps), at most ten times.
 *
 * The disk's four intersection routines - $6B0D, $6A92, $6A0D and the inline case at $6992 -
 * are exact parametric intersections with the same four planes. This solves for the same
 * point rather than transcribing their arithmetic, so a clipped endpoint can sit a unit away
 * from where the disk puts it; an endpoint that was already inside is untouched.
 */
export function clipFrustum61B7(a: Vec3, b: Vec3): { a: Vec3; b: Vec3 } | null {
  let p = { ...a };
  let q = { ...b };
  let op = outcode67EF(p);
  let oq = outcode67EF(q);

  for (let round = 0; round < CLIP_ROUNDS; round++) {
    if (!(op | oq)) return { a: p, b: q };   // both in
    if (op & oq) return null;                // $61BD BNE $620F - outside the same plane

    // $61BF looks at $66 first, so the far end is pulled in before the near one.
    const clipQ = oq !== 0;
    const out = clipQ ? oq : op;
    const from = clipQ ? p : q;
    const to = clipQ ? q : p;

    // The plane, and the value that has to become zero along the segment.
    const f = (v: Vec3): number =>
      out & OUT_LEFT ? v.x + v.z
        : out & OUT_RIGHT ? v.z - v.x
          : out & OUT_BOTTOM ? v.y + v.z
            : v.z - v.y;
    const fa = f(from), fb = f(to);
    const denom = fa - fb;
    if (denom === 0) return null;
    const t = fa / denom;
    const hit: Vec3 = {
      x: Math.round(from.x + (to.x - from.x) * t),
      y: Math.round(from.y + (to.y - from.y) * t),
      z: Math.round(from.z + (to.z - from.z) * t),
    };
    if (clipQ) { q = hit; oq = outcode67EF(q); } else { p = hit; op = outcode67EF(p); }
  }
  // $61D3 BEQ $620F - out of rounds is a rejection, not a draw.
  return null;
}
