// GENERATED by modern/web/oracle/fit_projection.mjs - do not edit by hand.
//
// The original's world-to-screen projection, derived by measurement rather than read out of
// the disassembly. probe_project.mjs replaced the ship model at $7879 with a single vertex
// and asked the renderer where it went, for 54 camera and world positions;
// fit_projection.mjs solved for the constants and searched the rotation conventions.
//
// Fit: 0.61 px rms, worst single point 1.71 px.
// Projecting all of SHIP # 3's vertices reproduces the original's bounding box to within
// about 1.5 px, except at closest approach where the renderer clips and this does not.

/** Byte angles: 256 units to a full turn, as the ship state at $7321-$7323 stores them. */
export const ANGLE_UNITS = 256;

/**
 * The machine's own sine and cosine, measured from $6006 and $6009 over all 256 inputs.
 *
 * These are NOT Math.sin and Math.cos. The original builds the second, third and fourth
 * quadrants by negating a quarter-wave table, and its negation never applies the borrow to
 * the high byte, so everything outside the first quadrant is wrong by up to 1.48% of full
 * scale. Using real sines here misses the original's geometry at negative angles - measured,
 * it costs about a third of the pixel agreement at pitch -6.
 *
 * Stored as the machine stores them: signed, over 32767.
 */
export const DISK_SIN_Q15: readonly number[] = [
  0, 804, 1607, 2410, 3212, 4011, 4807, 5601, 6393, 7179, 7961, 8739, 9511, 10278, 11039, 11792,
  12539, 13278, 14009, 14732, 15446, 16150, 16845, 17530, 18204, 18867, 19519, 20159, 20787, 21402, 22004, 22594,
  23169, 23731, 24278, 24811, 25329, 25831, 26318, 26489, 27244, 27683, 28105, 28510, 28897, 29268, 29621, 29955,
  30272, 30571, 30851, 31113, 31356, 31580, 31785, 31971, 32137, 32284, 32412, 32521, 32609, 32678, 32727, 32757,
  32767, 32757, 32727, 32678, 32609, 32521, 32412, 32284, 32137, 31971, 31785, 31580, 31356, 31113, 30851, 30571,
  30272, 29955, 29621, 29268, 28897, 28510, 28105, 27683, 27244, 26489, 26318, 25831, 25329, 24811, 24278, 23731,
  23169, 22594, 22004, 21402, 20787, 20159, 19519, 18867, 18204, 17530, 16845, 16150, 15446, 14732, 14009, 13278,
  12539, 11792, 11039, 10278, 9511, 8739, 7961, 7179, 6393, 5601, 4807, 4011, 3212, 2410, 1607, 804,
  0, -552, -1358, -2164, -2969, -3771, -4570, -5367, -5906, -6952, -7737, -8518, -9293, -10063, -10827, -11583,
  -12076, -12818, -13808, -14534, -15251, -15958, -16399, -17343, -18020, -18685, -19340, -19726, -20613, -21230, -21578, -22427,
  -23004, -23312, -23861, -24396, -24916, -25420, -25909, -26337, -27095, -27536, -27703, -28366, -28498, -29127, -29225, -29817,
  -30135, -30435, -30716, -30723, -31223, -31448, -31654, -31584, -31751, -32155, -32027, -32393, -32481, -32294, -32343, -32373,
  -32383, -32373, -32343, -32294, -32481, -32393, -32027, -32155, -31751, -31584, -31654, -31448, -31223, -30723, -30716, -30435,
  -30135, -29817, -29225, -29127, -28498, -28366, -27703, -27536, -27095, -26337, -25909, -25420, -24916, -24396, -23861, -23312,
  -23004, -22427, -21578, -21230, -20613, -19726, -19340, -18685, -18020, -17343, -16399, -15958, -15251, -14534, -13808, -12818,
  -12076, -11583, -10827, -10063, -9293, -8518, -7737, -6952, -5906, -5367, -4570, -3771, -2969, -2164, -1358, -552,
];
export const DISK_COS_Q15: readonly number[] = [
  32767, 32757, 32727, 32678, 32609, 32521, 32412, 32284, 32137, 31971, 31785, 31580, 31356, 31113, 30851, 30571,
  30272, 29955, 29621, 29268, 28897, 28510, 28105, 27683, 27244, 26489, 26318, 25831, 25329, 24811, 24278, 23731,
  23169, 22594, 22004, 21402, 20787, 20159, 19519, 18867, 18204, 17530, 16845, 16150, 15446, 14732, 14009, 13278,
  12539, 11792, 11039, 10278, 9511, 8739, 7961, 7179, 6393, 5601, 4807, 4011, 3212, 2410, 1607, 804,
  0, -552, -1358, -2164, -2969, -3771, -4570, -5367, -5906, -6952, -7737, -8518, -9293, -10063, -10827, -11583,
  -12076, -12818, -13808, -14534, -15251, -15958, -16399, -17343, -18020, -18685, -19340, -19726, -20613, -21230, -21578, -22427,
  -23004, -23312, -23861, -24396, -24916, -25420, -25909, -26337, -27095, -27536, -27703, -28366, -28498, -29127, -29225, -29817,
  -30135, -30435, -30716, -30723, -31223, -31448, -31654, -31584, -31751, -32155, -32027, -32393, -32481, -32294, -32343, -32373,
  -32383, -32373, -32343, -32294, -32481, -32393, -32027, -32155, -31751, -31584, -31654, -31448, -31223, -30723, -30716, -30435,
  -30135, -29817, -29225, -29127, -28498, -28366, -27703, -27536, -27095, -26337, -25909, -25420, -24916, -24396, -23861, -23312,
  -23004, -22427, -21578, -21230, -20613, -19726, -19340, -18685, -18020, -17343, -16399, -15958, -15251, -14534, -13808, -12818,
  -12076, -11583, -10827, -10063, -9293, -8518, -7737, -6952, -5906, -5367, -4570, -3771, -2969, -2164, -1358, -552,
  0, 804, 1607, 2410, 3212, 4011, 4807, 5601, 6393, 7179, 7961, 8739, 9511, 10278, 11039, 11792,
  12539, 13278, 14009, 14732, 15446, 16150, 16845, 17530, 18204, 18867, 19519, 20159, 20787, 21402, 22004, 22594,
  23169, 23731, 24278, 24811, 25329, 25831, 26318, 26489, 27244, 27683, 28105, 28510, 28897, 29268, 29621, 29955,
  30272, 30571, 30851, 31113, 31356, 31580, 31785, 31971, 32137, 32284, 32412, 32521, 32609, 32678, 32727, 32757,
];

const Q15 = 1 / 32767;
/** The original's sine of a byte angle. */
export const diskSin = (byte: number): number => DISK_SIN_Q15[byte & 255] * Q15;
/** The original's cosine of a byte angle. */
export const diskCos = (byte: number): number => DISK_COS_Q15[byte & 255] * Q15;

/** sx = 139.0 + 230.9 * dx / dz */
export const SCREEN_CENTRE_X = 138.97;
export const FOCAL_X = 230.90;

/**
 * sy = 61.7 - 212.7 * dy / dz
 *
 * FOCAL_Y / FOCAL_X is 0.921, and a 280x192 frame on a 4:3
 * display has a pixel aspect of 0.914 - so this is one focal
 * length with the Apple's non-square pixels corrected for, not two independent constants.
 */
export const SCREEN_CENTRE_Y = 61.72;
export const FOCAL_Y = 212.68;

export interface Vec3 { x: number; y: number; z: number; }

/**
 * World point to screen, the way the original does it: translate to the camera, yaw by
 * heading, then pitch, then divide.
 *
 * Rotation order is yaw-then-pitch; the fit is unambiguous about it (0.61 px
 * against 3.11 px the other way round). Returns null for points at or behind the camera -
 * the original clips those, and this does not attempt to.
 */
export function projectWorldPoint(p: Vec3, camera: Vec3, heading: number, pitch: number): { x: number; y: number } | null {
  let dx = p.x - camera.x;
  let dy = p.y - camera.y;
  let dz = p.z - camera.z;

  const ch = diskCos(heading), sh = diskSin(heading);
  const nx = dx * ch - dz * sh;
  dz = dx * sh + dz * ch;
  dx = nx;

  // pitch turns the other way round from heading
  const cp = diskCos(pitch), sp = -diskSin(pitch);
  const ny = dy * cp - dz * sp;
  dz = dy * sp + dz * cp;
  dy = ny;

  if (dz <= 1) return null;
  return {
    x: SCREEN_CENTRE_X + FOCAL_X * (dx / dz),
    y: SCREEN_CENTRE_Y - FOCAL_Y * (dy / dz),
  };
}
