// GENERATED by modern/web/oracle/fit_projection.mjs - do not edit by hand.
//
// The original's world-to-screen projection, derived by measurement rather than read out of
// the disassembly. probe_project.mjs replaced the ship model at $7879 with a single vertex
// and asked the renderer where it went, for 54 camera and world positions;
// fit_projection.mjs solved for the constants and searched the rotation conventions.
//
// Fit: 0.61 px rms, worst single point 1.71 px.
// Projecting all of SHIP # 3's vertices reproduces the original's bounding box to within
// about 1.5 px, except at closest approach where the renderer clips and this does not.

/** Byte angles: 256 units to a full turn, as the ship state at $7321-$7323 stores them. */
export const ANGLE_UNITS = 256;

/** sx = 139.0 + 230.9 * dx / dz */
export const SCREEN_CENTRE_X = 138.97;
export const FOCAL_X = 230.90;

/**
 * sy = 61.7 - 212.7 * dy / dz
 *
 * FOCAL_Y / FOCAL_X is 0.921, and a 280x192 frame on a 4:3
 * display has a pixel aspect of 0.914 - so this is one focal
 * length with the Apple's non-square pixels corrected for, not two independent constants.
 */
export const SCREEN_CENTRE_Y = 61.72;
export const FOCAL_Y = 212.68;

export interface Vec3 { x: number; y: number; z: number; }

/**
 * World point to screen, the way the original does it: translate to the camera, yaw by
 * heading, then pitch, then divide.
 *
 * Rotation order is yaw-then-pitch; the fit is unambiguous about it (0.61 px
 * against 3.11 px the other way round). Returns null for points at or behind the camera -
 * the original clips those, and this does not attempt to.
 */
export function projectWorldPoint(p: Vec3, camera: Vec3, heading: number, pitch: number): { x: number; y: number } | null {
  let dx = p.x - camera.x;
  let dy = p.y - camera.y;
  let dz = p.z - camera.z;

  const ah = ((heading & 255) / ANGLE_UNITS) * 2 * Math.PI;
  const ch = Math.cos(ah), sh = Math.sin(ah);
  const nx = dx * ch - dz * sh;
  dz = dx * sh + dz * ch;
  dx = nx;

  // pitch turns the other way round from heading
  const ap = ((pitch & 255) / ANGLE_UNITS) * 2 * Math.PI;
  const cp = Math.cos(ap), sp = -Math.sin(ap);
  const ny = dy * cp - dz * sp;
  dz = dy * sp + dz * cp;
  dy = ny;

  if (dz <= 1) return null;
  return {
    x: SCREEN_CENTRE_X + FOCAL_X * (dx / dz),
    y: SCREEN_CENTRE_Y - FOCAL_Y * (dy / dz),
  };
}
