/**
 * World to screen the way $6000 does it, end to end and entirely in fixed point.
 *
 * There used to be a `diskProjection.ts` beside this one, generated by a fit: it rotated with
 * floats, used focal lengths of 230.90 and 212.80 solved for from captures, and rotated by two
 * angles. The machine does none of that, this file superseded it stage by stage, and it has
 * been deleted. It builds a three-angle Q15 matrix with its own broken trig (`diskRotation.ts`),
 * scales the three camera axes by a per-object triple, multiplies through a 16-bit routine that
 * is not `a * b / 32768`, and divides with a non-restoring divide (`diskProjectionFixed.ts`).
 *
 *   $62CB  nine bytes of display list -> $90-$98   camera position, then pitch, bank, heading
 *   $62D5  JSR $654E                               build the matrix
 *   $6631  scale row 0/1/2 by $600E/$6010/$6012    the camera-axis scale
 *   $672B  the model point minus $90-$95           -> $AB/$AD/$AF
 *   $675B  M . that, through $633D and $67D4       -> $60-$65
 *   $6274  LDY #$60 / LDX #$9F / JSR $68A1         -> two screen bytes
 *   $6DD5  x + 70, doubled; 95 - y                 -> the hi-res page
 *
 * The fitted focal lengths turn out to be the scale: `2 * 69 * factor0 / factor2` is 231.42
 * and `62 * factor1 / factor2` is 212.93, against 230.90 and 212.80. So the fit was measuring
 * this, one step removed.
 *
 * Checked against 60 world points trapped from a live render by `oracle/probe_pipeline.mjs`,
 * at every stage: the translated vector, camera space, the two screen bytes, and the final
 * pixel. See `oracle/pipeline_parity.mjs`.
 */

import {
  buildMatrix654E, applyObjectScale, toCameraSpace6730, mul635C,
  SNAPSHOT_SCALE, type RotationMatrix,
} from './diskRotation';
import {
  project68A1, project68A1ToScreen, divide6468, SNAPSHOT_OPERANDS,
  type ProjectionOperands,
} from './diskProjectionFixed';
import { type Vec3 } from './math3d';

export type { Vec3 };

/**
 * The near plane, which is the port's and not the machine's.
 *
 * `$6468` divides by a negative z quite happily and `$68A1` returns the point mirrored through
 * the origin; the screen clipping at `$61A9` then usually throws it away. "Usually" is the
 * problem - a mirrored point that happens to land on the panel would be drawn - so points at or
 * behind z = 1 are dropped here instead. It came from the fitted float path and is kept because
 * the reasoning holds, not because the disk has a constant like it.
 */
export const NEAR_Z = 1;

/** Everything $6000 needs about one object, as the display list hands it over. */
export interface ObjectView {
  /** $90-$95 - the camera, in model units. */
  camera: Vec3;
  /** $96, $97, $98 - byte angles, 256 to the turn. */
  pitch: number;
  bank: number;
  heading: number;
  /** $600E-$6013 - the camera-axis scale. */
  scale: readonly [number, number, number];
  /** $68BA/$68C0/$68DD/$68E3 - the clamp limits and offsets. */
  ops: ProjectionOperands;
}

/** The flight snapshot's own view, as `oracle/probe_pipeline.mjs` read it at $6631. */
export const SNAPSHOT_VIEW: Omit<ObjectView, 'camera'> = {
  pitch: 0, bank: 0, heading: 0,
  scale: SNAPSHOT_SCALE,
  ops: SNAPSHOT_OPERANDS,
};

/**
 * $654E then $6631 - the matrix an object is actually transformed by.
 *
 * Worth hoisting out of any per-vertex loop: the machine builds it once per object, which is
 * what `$62D5` and the fall-through at `$6631` amount to.
 */
export function viewMatrix(view: ObjectView): RotationMatrix {
  return applyObjectScale(buildMatrix654E(view.pitch, view.bank, view.heading), view.scale);
}

const clamp16 = (v: number): number => (v > 32767 ? 32767 : v < -32768 ? -32768 : Math.round(v));

/**
 * $672B and $675B - a world point into camera space, with the matrix already built.
 *
 * The machine works in whole model units throughout, so the coordinates are rounded and held
 * to sixteen bits on the way in. A clipped endpoint is the only thing that arrives fractional,
 * and rounding it is the one place this departs from the disk - the disk never has one,
 * because it clips on the screen rather than at a near plane.
 */
export function toCameraSpaceFixed(p: Vec3, camera: Vec3, m: RotationMatrix): Vec3 {
  const d = toCameraSpace6730(
    [clamp16(p.x), clamp16(p.y), clamp16(p.z)],
    [clamp16(camera.x), clamp16(camera.y), clamp16(camera.z)],
    m,
  );
  return { x: d[0], y: d[1], z: d[2] };
}

/**
 * $68A1 and $6DD5 - camera space to a pixel, or null behind the near plane.
 *
 * The machine has no near plane: `$6468` divides by a negative z quite happily and `$68A1`
 * returns a point that is mirrored through the origin, which the screen clipping at `$61A9`
 * then usually throws away. The port cannot rely on that, because `insideClip()` would let a
 * mirrored point through whenever it happened to land on the panel - so the same `z < NEAR_Z`
 * test `projectCameraSpace()` uses is kept.
 */
export function projectCameraSpaceFixed(
  d: Vec3,
  ops: ProjectionOperands = SNAPSHOT_OPERANDS,
): { x: number; y: number } | null {
  if (d.z < NEAR_Z) return null;
  return project68A1ToScreen(clamp16(d.x), clamp16(d.y), clamp16(d.z), ops);
}

/** The two screen bytes as $68A1 writes them, before $6DD5 maps them. */
export function projectCameraSpaceBytes(
  d: Vec3,
  ops: ProjectionOperands = SNAPSHOT_OPERANDS,
): { sx: number; sy: number } {
  return project68A1(clamp16(d.x), clamp16(d.y), clamp16(d.z), ops);
}

/** The whole chain for a single point, when there is no loop to hoist the matrix out of. */
export function projectWorldPointFixed(
  p: Vec3,
  view: ObjectView,
): { x: number; y: number } | null {
  return projectCameraSpaceFixed(toCameraSpaceFixed(p, view.camera, viewMatrix(view)), view.ops);
}

/** Re-exported so callers do not have to reach past this module for the primitive. */
export { mul635C };

/**
 * $67EF - the camera-space outcode, four bits.
 *
 * Each plane is tested by a 16-bit add or subtract followed by the `BMI/BVC/BVS` dance that
 * asks whether N and V disagree, which is the signed "is this negative" test:
 *
 *     $67F1  x + z < 0   ->  $40      the left plane,   x = -z
 *     $6804  z - x < 0   ->  $20      the right plane,  x = z
 *     $6819  y + z < 0   ->  $10      the bottom plane, y = -z
 *     $682E  z - y < 0   ->  $08      the top plane,    y = z
 *
 * So the frustum is |x| <= z and |y| <= z: ninety degrees each way, in camera space and after
 * the object scale. That is exactly the region where `$68A1` does not wrap - x/z of 1 is the
 * clamp limit - which is why the disk never draws the folded-over points a naive port does.
 * A point behind the camera always has a bit set, since |x| <= z is impossible for z < 0, so
 * there is no separate near-plane test.
 *
 * `$6848` is the same routine for the second slot at $68, writing $6E instead of $66.
 */
export const OUT_LEFT = 0x40;
export const OUT_RIGHT = 0x20;
export const OUT_BOTTOM = 0x10;
export const OUT_TOP = 0x08;

export function outcode67EF(d: Vec3): number {
  let o = 0;
  if (d.x + d.z < 0) o |= OUT_LEFT;
  if (d.z - d.x < 0) o |= OUT_RIGHT;
  if (d.y + d.z < 0) o |= OUT_BOTTOM;
  if (d.z - d.y < 0) o |= OUT_TOP;
  return o;
}

/** $615E - `LDA #$0A / STA $B1`, the budget the clipper spends across both ends. */
export const CLIP_ROUNDS = 10;

const w16 = (v: number): number => {
  const u = v & 0xffff;
  return u > 32767 ? u - 65536 : u;
};

/**
 * $6992, $6A0D, $6A92, $6B0D - pull the far end of a segment onto one plane.
 *
 * All four are the same nine steps with the axes and signs swapped. For the plane `y = z`
 * at $6992, with A at $60-$65 and B at $68-$6D:
 *
 *     $6992  $7A = az - bz
 *     $699F  $7A = (ay - by) - (az - bz)          the denominator
 *     $69B5  A:X = bz - by                        the numerator
 *     $69BF  JSR $6468                            t, as a Q15 fraction in $78/$79
 *     $69C2  bx += t * (ax - bx)                  through $635C
 *     $69E4  bz += t * (az - bz)
 *     $6A01  by = bz                              the plane, set rather than computed
 *     $6A0A  JMP $6848                            and B's outcode is recomputed
 *
 * Solving `by + t(ay - by) = bz + t(az - bz)` gives exactly that t. The axis the plane names
 * is assigned from the new z instead of interpolated, so it lands on the plane exactly: at
 * $6A0D and $6B0D, where the plane is negative, it is `EOR #$FF` and `INC`, a two's
 * complement of the new z.
 */
const PLANES = [
  {
    bit: OUT_TOP,                                         // $6992 - y = z
    num: (a: Vec3, b: Vec3): number => b.z - b.y,
    den: (a: Vec3, b: Vec3): number => (a.y - b.y) - (a.z - b.z),
    free: 'x' as const, sign: 1,
  },
  {
    bit: OUT_BOTTOM,                                      // $6A0D - y = -z
    num: (a: Vec3, b: Vec3): number => b.z + b.y,
    den: (a: Vec3, b: Vec3): number => (b.y - a.y) - (a.z - b.z),
    free: 'x' as const, sign: -1,
  },
  {
    bit: OUT_RIGHT,                                       // $6A92 - x = z
    num: (a: Vec3, b: Vec3): number => b.z - b.x,
    den: (a: Vec3, b: Vec3): number => (a.x - b.x) - (a.z - b.z),
    free: 'y' as const, sign: 1,
  },
  {
    bit: OUT_LEFT,                                        // $6B0D - x = -z
    num: (a: Vec3, b: Vec3): number => b.z + b.x,
    den: (a: Vec3, b: Vec3): number => (b.x - a.x) - (a.z - b.z),
    free: 'y' as const, sign: -1,
  },
];

/**
 * $6979 - clip B against whichever plane its outcode names.
 *
 * The dispatch asks, in turn, whether $40 is the only bit left, then whether $40 and $20 are,
 * then $10 as well - so the test that matches is the **last** bit still set, and the priority
 * runs $08, $10, $20, $40. A corner outside both x = z and y = z is taken against y = z
 * first, which is the opposite of the order the masks are written in.
 */
export function clipEnd6979(a: Vec3, b: Vec3, outcodeB: number): Vec3 {
  const plane = PLANES.find((p) => outcodeB & p.bit);
  if (!plane) return b;
  const den = plane.den(a, b);
  if (den === 0) return b;
  const t = divide6468(plane.num(a, b), den);
  const other = plane.free;
  const axis = plane.free === 'x' ? 'y' : 'x';
  const z = w16(b.z + mul635C(t, w16(a.z - b.z)));
  const out: Vec3 = { x: b.x, y: b.y, z };
  out[other] = w16(b[other] + mul635C(t, w16(a[other] - b[other])));
  out[axis] = plane.sign === 1 ? z : w16(-z);
  return out;
}

/**
 * $61B7 - clip a camera-space segment to the frustum, or drop it.
 *
 * `JSR $61A9 / JSR $618E / BNE $620F` transforms both ends, takes both outcodes and rejects
 * outright when `$66 AND $6E` is nonzero - both outside the same plane. Then A is pulled in
 * first and B after, one plane per round:
 *
 *     $61BF  LDA $66 / BNE $61D7      A outside -> $61DB JSR $695F, clip A
 *     $61DE  LDA $66 / BEQ $61C3      A is in now, go and look at B
 *     $61E2  AND $6E / BNE $620F      still out, and sharing a plane with B -> reject
 *     $61C3  LDA $6E / BNE $61CA      B outside -> $61CE JSR $6979, clip B
 *     $61C7  JMP $627A                both in, draw it
 *
 * `$695F` is `$6979` between two calls to `$6969`, which swaps the eight bytes of each slot -
 * outcodes included - so clipping A is clipping B with the ends exchanged.
 *
 * `$B1` is one budget of ten spent across both ends, and running out is a rejection, not a
 * draw. `$7C` is a per-object flag from the display list ($62BE): when it is set, a segment
 * that needs clipping is dropped rather than clipped.
 */
export function clipFrustum61B7(
  a: Vec3,
  b: Vec3,
  noClip = 0,
): { a: Vec3; b: Vec3 } | null {
  let p = { ...a };
  let q = { ...b };
  let op = outcode67EF(p);
  let oq = outcode67EF(q);
  if (op & oq) return null;                       // $61BD
  let budget = CLIP_ROUNDS;

  while (op) {                                    // $61D7 - A first
    if (noClip) return null;                      // $61D9
    p = clipEnd6979(q, p, op);                    // $61DB JSR $695F
    op = outcode67EF(p);
    if (!op) break;                               // $61E0 BEQ $61C3
    if (op & oq) return null;                     // $61E4
    if (--budget === 0) return null;              // $61E6 DEC $B1 / $61EA BEQ $620F
  }
  while (oq) {                                    // $61C3 - then B
    if (noClip) return null;                      // $61CC
    q = clipEnd6979(p, q, oq);                    // $61CE JSR $6979
    oq = outcode67EF(q);
    if (--budget === 0) return null;              // $61D1 DEC $B1 / $61D3 BEQ $620F
  }
  return { a: p, b: q };                          // $61C7 JMP $627A
}
