// GENERATED by modern/web/oracle/probe_planetdata.mjs - do not edit by hand.
//
// Decoded from PLANET FILE-M on the original disk, indexed the way the game indexes it.
// Each field is located by a use site in the original BASIC, quoted beside it; the tables
// do not share a base, so a single base for all of them puts half the data off by one.
//
// Planets are numbered 1..20. GALAXY MAP loops FOR P = 1 TO 20, and PEEK(38209) - the
// current planet - is compared against P inside that loop and used to index X()/Y()/Z().

export interface DiskPlanet {
  /** 1..20, as the original numbers them. */
  planet: number;
  /** GALAXY MAP 3066: IF PEEK(38219 + P) = 1 THEN HCOLOR= 2 */
  flag: number;
  /** GALAXY MAP 3020: X(P) = PEEK(M + P), M = 38366 */
  x: number;
  /** GALAXY MAP 3020: Y(P) = PEEK((M + P) - 21) */
  y: number;
  /** GALAXY MAP 3020: Z(P) = PEEK((M + P) - 42) */
  z: number;
  /**
   * STARSHIP SIMULATOR 8: TE = PEEK(38282 + PEEK(38209))
   * STARSHIP SIMULATOR 189: IF PEEK(38282 + PEEK(38209)) < 2 THEN (no enemies appear)
   */
  defence: number;
}

export const DISK_PLANETS: readonly DiskPlanet[] = [
  { planet: 1, flag: 1, x: 15, y: 15, z: 15, defence: 3 },
  { planet: 2, flag: 0, x: 13, y: 13, z: 12, defence: 3 },
  { planet: 3, flag: 0, x: 14, y: 9, z: 15, defence: 3 },
  { planet: 4, flag: 0, x: 8, y: 16, z: 12, defence: 0 },
  { planet: 5, flag: 0, x: 22, y: 14, z: 19, defence: 2 },
  { planet: 6, flag: 0, x: 13, y: 22, z: 19, defence: 1 },
  { planet: 7, flag: 0, x: 17, y: 23, z: 12, defence: 4 },
  { planet: 8, flag: 0, x: 14, y: 8, z: 9, defence: 2 },
  { planet: 9, flag: 0, x: 19, y: 13, z: 25, defence: 3 },
  { planet: 10, flag: 0, x: 20, y: 22, z: 10, defence: 4 },
  { planet: 11, flag: 0, x: 9, y: 23, z: 20, defence: 0 },
  { planet: 12, flag: 0, x: 7, y: 23, z: 14, defence: 1 },
  { planet: 13, flag: 0, x: 25, y: 21, z: 13, defence: 4 },
  { planet: 14, flag: 0, x: 25, y: 15, z: 21, defence: 2 },
  { planet: 15, flag: 0, x: 9, y: 21, z: 19, defence: 0 },
  { planet: 16, flag: 0, x: 25, y: 5, z: 11, defence: 3 },
  { planet: 17, flag: 0, x: 24, y: 10, z: 10, defence: 3 },
  { planet: 18, flag: 0, x: 11, y: 18, z: 27, defence: 3 },
  { planet: 19, flag: 0, x: 18, y: 27, z: 11, defence: 1 },
  { planet: 20, flag: 0, x: 11, y: 11, z: 25, defence: 2 },
] as const;

/** The original refuses to spawn defenders below 2. STARSHIP SIMULATOR line 189. */
export const DEFENCE_SPAWN_THRESHOLD = 2;
