// GENERATED by modern/web/oracle/probe_planetdata.mjs - do not edit by hand.
//
// The galaxy, decoded from PLANET FILE-M, P/F-M and GALAXY MAP on the original disk.
//
// PLANET FILE is eight 21-byte tables, each read as base + P with base = 38219 + 21k:
// 8 * 21 = 168 bytes, then 7 control bytes, which is its 175 exactly. Every base below is
// a literal that appears in the BASIC, quoted beside the field it fills. They do NOT share
// a base, so reading the file as one array of records puts most of the data off by one.
//
// The disk numbers planets 1..20 (GALAXY MAP 15100: S$(1) = "SOL"). DISK_PLANETS is
// 0-based to match the port's own convention, so DISK_PLANETS[i] is the disk's planet
// i + 1, and index 0 is SOL - the planet a new game starts at.

export interface DiskPlanet {
  /** The disk's own number, 1..20. This is DISK_PLANETS index + 1. */
  planet: number;
  /** GALAXY MAP 15100-15130: S$(P). Upper case, as the original prints it. */
  name: string;
  /** 38219+P. COM 1120/1130: PRINT S$(C);" HAS BEEN SECURED" - the planet is yours. */
  secured: boolean;
  /** 38240+P. COM 1005: IF PEEK(38240+C) = 0 THEN "NO INFORMATION AVAILABLE AT THIS TIME." */
  known: boolean;
  /** 38261+P. COM 1110: PRINT "POPULATION = APPROX. "; PEEK(38261+C) * 35294. */
  population: number;
  /**
   * 38282+P. GROUND FORCES 500 names it: TECH = PEEK(38209): TECH = PEEK(38282 + TECH).
   * STARSHIP SIMULATOR 189: defenders only appear at tech >= 2.
   */
  tech: number;
  /** 38303+P. COM 1150/1160: "THERE IS AN OPERATIONAL REPAIR BASE ON THE PLANET." */
  repairBase: boolean;
  /** 38324+P. GALAXY MAP 3020: Z(P) = PEEK((M + P) - 42), M = 38366. */
  z: number;
  /** 38345+P. GALAXY MAP 3020: Y(P) = PEEK((M + P) - 21). */
  y: number;
  /** 38366+P. GALAXY MAP 3020: X(P) = PEEK(M + P). */
  x: number;

  // The rest come from the planet's P/F record. START line 220 calls into TRANLIT.OBJ0,
  // which copies that record to $953C-$9541, and the BASIC then peeks it there.

  /** $953C. H/D 93: POKE 38204, TECH * 60. */
  destructionLimit: number;
  /**
   * $953D, raw. START 230: J = PEEK(38205): IF J = 2 THEN J = 3 - there is no SHIP # 2 on
   * the disk. Use resolveShipKind() rather than this value.
   */
  shipKind: number;
  /** $953E. GROUND FORCES 500: enemy ground troops = this * 500. */
  groundTroopUnits: number;
  /** $953F. STARSHIP SIMULATOR 190/192: defenders only spawn while this is > 0. */
  enemyShips: number;
  /** $9540. STARSHIP SIMULATOR 190/192: spawning also requires this to be 0. */
  noSpawn: number;
}

export const DISK_PLANETS: readonly DiskPlanet[] = [
  { planet: 1, name: "SOL", secured: true, known: true, population: 125, tech: 3, repairBase: true, x: 15, y: 15, z: 15, destructionLimit: 150, shipKind: 3, groundTroopUnits: 100, enemyShips: 30, noSpawn: 1 },
  { planet: 2, name: "ALPHA CENTAURI", secured: false, known: false, population: 70, tech: 3, repairBase: false, x: 13, y: 13, z: 12, destructionLimit: 100, shipKind: 2, groundTroopUnits: 50, enemyShips: 20, noSpawn: 0 },
  { planet: 3, name: "BARNARD'S STAR", secured: false, known: false, population: 175, tech: 3, repairBase: false, x: 14, y: 9, z: 15, destructionLimit: 150, shipKind: 3, groundTroopUnits: 120, enemyShips: 22, noSpawn: 0 },
  { planet: 4, name: "WOLF 359", secured: false, known: false, population: 0, tech: 0, repairBase: false, x: 8, y: 16, z: 12, destructionLimit: 0, shipKind: 0, groundTroopUnits: 0, enemyShips: 0, noSpawn: 1 },
  { planet: 5, name: "LUYTEN", secured: false, known: false, population: 90, tech: 2, repairBase: false, x: 22, y: 14, z: 19, destructionLimit: 20, shipKind: 1, groundTroopUnits: 20, enemyShips: 0, noSpawn: 0 },
  { planet: 6, name: "LALANDE 21185", secured: false, known: false, population: 3, tech: 1, repairBase: false, x: 13, y: 22, z: 19, destructionLimit: 0, shipKind: 0, groundTroopUnits: 5, enemyShips: 0, noSpawn: 0 },
  { planet: 7, name: "SIRIUS", secured: false, known: false, population: 200, tech: 4, repairBase: false, x: 17, y: 23, z: 12, destructionLimit: 200, shipKind: 4, groundTroopUnits: 150, enemyShips: 20, noSpawn: 0 },
  { planet: 8, name: "VARCAR", secured: false, known: false, population: 150, tech: 2, repairBase: false, x: 14, y: 8, z: 9, destructionLimit: 20, shipKind: 1, groundTroopUnits: 100, enemyShips: 0, noSpawn: 0 },
  { planet: 9, name: "XANADON", secured: false, known: false, population: 85, tech: 3, repairBase: false, x: 19, y: 13, z: 25, destructionLimit: 100, shipKind: 2, groundTroopUnits: 100, enemyShips: 40, noSpawn: 0 },
  { planet: 10, name: "EPSILON ERIDANA", secured: false, known: false, population: 157, tech: 4, repairBase: false, x: 20, y: 22, z: 10, destructionLimit: 150, shipKind: 3, groundTroopUnits: 120, enemyShips: 25, noSpawn: 0 },
  { planet: 11, name: "CYGNI", secured: false, known: false, population: 0, tech: 0, repairBase: false, x: 9, y: 23, z: 20, destructionLimit: 0, shipKind: 0, groundTroopUnits: 0, enemyShips: 0, noSpawn: 1 },
  { planet: 12, name: "PROCYON", secured: false, known: false, population: 1, tech: 1, repairBase: false, x: 7, y: 23, z: 14, destructionLimit: 0, shipKind: 0, groundTroopUnits: 0, enemyShips: 0, noSpawn: 1 },
  { planet: 13, name: "TAU CETI", secured: false, known: false, population: 165, tech: 4, repairBase: false, x: 25, y: 21, z: 13, destructionLimit: 200, shipKind: 4, groundTroopUnits: 200, enemyShips: 50, noSpawn: 0 },
  { planet: 14, name: "LACAILLE 9352", secured: false, known: false, population: 6, tech: 2, repairBase: false, x: 25, y: 15, z: 21, destructionLimit: 20, shipKind: 1, groundTroopUnits: 7, enemyShips: 0, noSpawn: 0 },
  { planet: 15, name: "LARSEN-C", secured: false, known: false, population: 0, tech: 0, repairBase: false, x: 9, y: 21, z: 19, destructionLimit: 0, shipKind: 0, groundTroopUnits: 0, enemyShips: 0, noSpawn: 1 },
  { planet: 16, name: "GROOMBRIDGE 168", secured: false, known: false, population: 80, tech: 3, repairBase: false, x: 25, y: 5, z: 11, destructionLimit: 100, shipKind: 2, groundTroopUnits: 95, enemyShips: 20, noSpawn: 0 },
  { planet: 17, name: "KRUGER 60", secured: false, known: false, population: 130, tech: 3, repairBase: false, x: 24, y: 10, z: 10, destructionLimit: 150, shipKind: 3, groundTroopUnits: 100, enemyShips: 40, noSpawn: 0 },
  { planet: 18, name: "EPSILON INDI", secured: false, known: false, population: 155, tech: 3, repairBase: false, x: 11, y: 18, z: 27, destructionLimit: 150, shipKind: 3, groundTroopUnits: 115, enemyShips: 26, noSpawn: 0 },
  { planet: 19, name: "ARGO", secured: false, known: false, population: 2, tech: 1, repairBase: false, x: 18, y: 27, z: 11, destructionLimit: 0, shipKind: 0, groundTroopUnits: 5, enemyShips: 0, noSpawn: 0 },
  { planet: 20, name: "SHIVANDA", secured: false, known: false, population: 7, tech: 2, repairBase: false, x: 11, y: 11, z: 25, destructionLimit: 20, shipKind: 1, groundTroopUnits: 15, enemyShips: 0, noSpawn: 0 },
] as const;

/** START line 230: J = PEEK(38205): IF J = 2 THEN J = 3. Ship files on disk are 0, 1, 3, 4. */
export function resolveShipKind(kind: number): number {
  return kind === 2 ? 3 : kind;
}

/** COM 1110: PRINT "POPULATION = APPROX. "; PEEK(38261 + C) * 35294. */
export const POPULATION_SCALE = 35294;

/** GROUND FORCES 500: ET = PEEK(38206) * 500. */
export const GROUND_TROOPS_PER_UNIT = 500;

/** STARSHIP SIMULATOR 189: IF PEEK(38282 + PEEK(38209)) < 2 THEN (no enemies appear). */
export const TECH_SPAWN_THRESHOLD = 2;
