// The planet tables, decoded from the master files and indexed the way the game indexes
// them.
//
// Every table below is located by a use site in the BASIC, not by pattern-matching the
// bytes. That matters because the tables do NOT share a base: the galaxy map reads flags
// at PEEK(38219+P) — offset P-1 — while flight reads the defender level at
// PEEK(38282+PEEK(38209)) — offset 62+P. Guessing one base for all of them puts half the
// data off by one.
//
// Planets are numbered 1..20: GALAXY MAP loops FOR P = 1 TO 20, and PEEK(38209) (the
// current planet) is compared against P inside that loop and used to index X()/Y()/Z().
import { openDisk, DISK } from './dsk.mjs';
import fs from 'fs';

const PF = 0x954c;                                     // where PLANET FILE BLOADs
const d = openDisk(DISK);
const pf = d.read(d.files.find((f) => f.name === 'PLANET FILE-M')).data;
const at = (addr) => pf[addr - PF];

const PLANETS = [];
for (let p = 1; p <= 20; p++) {
  PLANETS.push({
    planet: p,
    // GALAXY MAP 3066: IF PEEK(38219 + P) = 1 THEN HCOLOR= 2
    flag: at(38219 + p),
    // GALAXY MAP 3020: X(P)=PEEK(M+P), Y(P)=PEEK((M+P)-21), Z(P)=PEEK((M+P)-42), M=38366
    x: at(38366 + p), y: at(38345 + p), z: at(38324 + p),
    // STARSHIP SIMULATOR 8: TE = PEEK(38282 + PEEK(38209))
    // STARSHIP SIMULATOR 189: IF PEEK(38282 + PEEK(38209)) < 2 THEN (no enemies)
    defence: at(38282 + p),
  });
}

// P/F-M is 21 fixed 16-byte records; byte 5 of each is the planet number it belongs to.
const pfm = d.read(d.files.find((f) => f.name === 'P/F-M')).data;
const RECORDS = [];
for (let i = 0; i + 16 <= pfm.length; i += 16) {
  const r = pfm.subarray(i, i + 16);
  if (r[5] === 0 || r[5] > 20) continue;               // the trailing filler record
  RECORDS.push({ planet: r[5], w0: r[0] | (r[1] << 8), b2: r[2], b3: r[3], b4: r[4], at: i });
}

const out = { planets: PLANETS, pf: RECORDS, notes: {
  'PLANET FILE base': '$954C (38220)',
  'unused offset 62': `at $9586 = ${at(38282)} — offset 62 is never read: the defence table is indexed 38282+P for P=1..20, so it starts at offset 63`,
  'save sentinel $95F7': `${at(38391)} (77 once a game has been saved; START line 26)`,
} };
fs.writeFileSync('captured/planet_data.json', JSON.stringify(out, null, 2) + '\n');

console.log('PLANET FILE-M, indexed as the game indexes it\n');
console.log(' P  flag    X   Y   Z   defence');
for (const p of PLANETS) console.log(`${String(p.planet).padStart(2)}  ${p.flag}     ` +
  `${String(p.x).padStart(3)} ${String(p.y).padStart(3)} ${String(p.z).padStart(3)}   ${p.defence}`);

console.log('\nP/F-M records\n');
console.log(' P   word0   b2   b3  b4');
for (const r of RECORDS) console.log(`${String(r.planet).padStart(2)}  ${String(r.w0).padStart(6)}  ` +
  `${String(r.b2).padStart(3)}  ${String(r.b3).padStart(3)}  ${r.b4}`);

// --- the port -------------------------------------------------------------------------
const src = fs.readFileSync('../src/engine/extractedOriginalData.ts', 'utf8');
const rows = [...src.matchAll(/\{\s*planet:\s*(\d+),\s*tech:\s*(\d+),\s*base:\s*(\d+),\s*conquered:\s*(\d+)/g)]
  .map((m) => ({ planet: +m[1], tech: +m[2], base: +m[3], conquered: +m[4] }));

console.log(`\n--- the port's EXTRACTED_LIVE_PLANET_TABLE: ${rows.length} rows, planets ` +
  `${rows[0].planet}..${rows[rows.length - 1].planet} ---`);

// Does the port's tech column match the disk's defence table, and at what offset?
const disk = [...Array(21)].map((_, i) => at(38282 + i));   // offsets 62..82
for (const shift of [0, 1]) {
  const hits = rows.filter((r, i) => r.tech === disk[i + shift]).length;
  console.log(`  port row i vs PLANET FILE offset ${62 + shift} + i: ${hits}/${rows.length} match` +
    (shift === 1 ? '   <- this is the indexing the game uses (planet P at offset 62+P)' : ''));
}
console.log(`\n  the disk's planet 20 has defence ${at(38282 + 20)}; the port has no planet 20.`);
console.log(`  offset 62 (value ${at(38282)}) is not a planet — no planet number indexes it.`);

// --- emit the verified table ----------------------------------------------------------
// Generated, not hand-maintained: the disk is the source, and this file says so at the top
// so nobody edits it by hand and nobody mistakes it for the unverified table beside it.
const ts = `// GENERATED by modern/web/oracle/probe_planetdata.mjs - do not edit by hand.
//
// Decoded from PLANET FILE-M on the original disk, indexed the way the game indexes it.
// Each field is located by a use site in the original BASIC, quoted beside it; the tables
// do not share a base, so a single base for all of them puts half the data off by one.
//
// Planets are numbered 1..20. GALAXY MAP loops FOR P = 1 TO 20, and PEEK(38209) - the
// current planet - is compared against P inside that loop and used to index X()/Y()/Z().

export interface DiskPlanet {
  /** 1..20, as the original numbers them. */
  planet: number;
  /** GALAXY MAP 3066: IF PEEK(38219 + P) = 1 THEN HCOLOR= 2 */
  flag: number;
  /** GALAXY MAP 3020: X(P) = PEEK(M + P), M = 38366 */
  x: number;
  /** GALAXY MAP 3020: Y(P) = PEEK((M + P) - 21) */
  y: number;
  /** GALAXY MAP 3020: Z(P) = PEEK((M + P) - 42) */
  z: number;
  /**
   * STARSHIP SIMULATOR 8: TE = PEEK(38282 + PEEK(38209))
   * STARSHIP SIMULATOR 189: IF PEEK(38282 + PEEK(38209)) < 2 THEN (no enemies appear)
   */
  defence: number;
}

export const DISK_PLANETS: readonly DiskPlanet[] = [
${PLANETS.map((p) => `  { planet: ${p.planet}, flag: ${p.flag}, x: ${p.x}, y: ${p.y}, z: ${p.z}, defence: ${p.defence} },`).join('\n')}
] as const;

/** The original refuses to spawn defenders below 2. STARSHIP SIMULATOR line 189. */
export const DEFENCE_SPAWN_THRESHOLD = 2;
`;
fs.writeFileSync('../src/engine/diskPlanetData.ts', ts);
console.log('\nwrote ../src/engine/diskPlanetData.ts');
